### ISSUE TITLE
Typo error?

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/Java4Python#6]
Error reported in course java4python on page TowerofHanoi by user html christophergkhui@gmail.com
"Here is a high-level outline of how to move a tower from the starting pole, to the goal pole, using an intermediate pole:

Move a tower of height-1 to an intermediate pole, using the final pole."

I'm confused about the first step in this passage. Isn't it moving the tower of height - 1 to the intermediary pole using the INITIAL pole?

**Comment by bnmnetp** [comment]
No, you have to move the tower of height-1 to an intermediate pole so you can move the largest disc (the one on the bottom) to the final pole. THEN move the height-1 pole to the final pole using the initial pole.
